#!/usr/bin/env bash

set -eo pipefail
IFS=$'\n\t'

DIST=$(uname)

case $DIST in
  Darwin)
    INSTALL_PATH='/usr/local/bin'
    ;;
  Linux)
    INSTALL_PATH='/usr/bin'
   ;;
  *)
    echo "Unsupported distro $DIST"
    exit 1
  ;;
esac

cat << EOF >> ~/.ssh/config
Host github.com bitbucket.org
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
EOF

install_cmd() {
  local cmd=$@
  if [ `whoami` == 'root' ]; then
    `$@`
  else
    `sudo $@`
  fi
}

install_cmd ln -sf ~/.toolbox/retry $INSTALL_PATH/retry
install_cmd chmod +x $INSTALL_PATH/retry

install_cmd ln -sf ~/.toolbox/ssh-session-cli $INSTALL_PATH/semaphore
install_cmd chmod +x $INSTALL_PATH/semaphore

install_cmd ln -sf ~/.toolbox/cache $INSTALL_PATH/cache
install_cmd chmod +x $INSTALL_PATH/cache

install_cmd ln -sf ~/.toolbox/sem-service $INSTALL_PATH/sem-service
install_cmd chmod +x $INSTALL_PATH/sem-service
