#!/usr/bin/env bash

set -eo pipefail
IFS=$'\n\t'

sudo ln -sf ~/.toolbox/libcheckout /usr/bin/libcheckout
sudo chmod +x /usr/bin/libcheckout

sudo ln -sf ~/.toolbox/retry /usr/bin/retry
sudo chmod +x /usr/bin/retry

sudo ln -sf ~/.toolbox/ssh-session-cli /usr/bin/semaphore
sudo chmod +x /usr/bin/semaphore

sudo ln -sf ~/.toolbox/cache /usr/bin/cache
sudo chmod +x /usr/bin/cache

sudo ln -sf ~/.toolbox/sem-service /usr/bin/sem-service
sudo chmod +x /usr/bin/sem-service
