#!/usr/bin/env bash

params-check::mysql () {
  default_params='--net=host --rm -d  -v /var/tmp/mysql:/var/lib/mysql --name mysql -v /var/run/mysqld:/var/run/mysqld '
  service_version="5.6"
  sudo mkdir -p /var/run/mysqld && sudo chmod -R 0777 /var/run/mysqld
  sudo mkdir -p /var/tmp/mysqld && sudo chmod -R 0777 /var/tmp/mysqld
  params=""
  local password="";
  local username="";
  local db=" -e MYSQL_DATABASE=test ";
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi

  if [ "$default_params" != "$params" ];then
    for words in $params; do
      case $words in
       --username=* )
         username="$(echo $words|cut -d'=' -f2)"
       ;;
       --password=* )
         password="$(echo $words|cut -d'=' -f2)"
       ;;
       --db=* )
         db="  -e MYSQL_DATABASE=$(echo $words|cut -d'=' -f2) "
       ;;
       *)
       ;;
      esac
    done
  fi
  if [ "$username" = "" ] || [ "$username" = "root" ]; then
    username=""
    if [ "$password" ]; then 
      password=" -e MYSQL_ROOT_PASSWORD=$password "
    else
      password=" -e MYSQL_ALLOW_EMPTY_PASSWORD=yes "
    fi
  else
    username=" -e MYSQL_USER=$username "
    password=" -e MYSQL_PASSWORD=$password  -e MYSQL_ALLOW_EMPTY_PASSWORD=yes "
  fi

  default_params="$default_params$username$password$db "
  echo "$service_version $default_params"
}

params-check::postgres () {
  default_params='--net=host --rm -d -e POSTGRES_PASSWORD=semaphore --name postgres -v /var/tmp/postgres:/var/lib/postgresql/data -v /var/run/postgresql:/var/run/postgresql'
  service_version="9.6"
  sudo mkdir -p /var/run/postgresql && sudo chmod -R 0777 /var/run/postgresql
  sudo mkdir -p /var/tmp/postgres && sudo chmod -R 0777 /var/tmp/postgres
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi
  if [ "$default_params" != "$params" ];then
    username=""; password=""; db=""; dbname="";
    for words in $params; do
      case $words in
       --username=* )
         username=" -e POSTGRES_USER=$(echo $words|cut -d'=' -f2) "
       ;;
       --password=* )
         password=$(echo $words|cut -d'=' -f2) 
         password=" -e POSTGRES_PASSWORD=${password:-'postgres'}"
       ;;
       --db=* )
         dbname=$(echo $words|cut -d'=' -f2)
       ;;
       *)
       ;;
      esac
    done
    [ "$dbname" ] && db=" -e POSTGRES_DB=$dbname"
    [ "$username$password" ] && default_params="$default_params$username$password$db "
  fi
  echo "$service_version $default_params"
}
params-check::postgis () {
  default_params='--net=host --rm -d -e POSTGRES_PASSWORD=semaphore --name postgis -v /var/tmp/postgres:/var/lib/postgresql/data -v /var/run/postgresql:/var/run/postgresql'
  service_version="9.6-2.5"
  sudo rm -rf /var/run/postgresql /var/tmp/postgres
  sudo mkdir -p /var/run/postgresql && sudo chmod -R 0777 /var/run/postgresql
  sudo mkdir -p /var/tmp/postgres && sudo chmod -R 0777 /var/tmp/postgres
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi
  if [ "$default_params" != "$params" ];then
    username=""; password=""; db=""; dbname="";
    for words in $params; do
      case $words in
       --username=* )
         username=" -e POSTGRES_USER=$(echo $words|cut -d'=' -f2) "
       ;;
       --password=* )
         password=$(echo $words|cut -d'=' -f2) 
         password=" -e POSTGRES_PASSWORD=${password:-'semaphore'}"
       ;;
       --db=* )
         dbname=$(echo $words|cut -d'=' -f2)
       ;;
       *)
       ;;
      esac
    done
    [ "$dbname" ] && db=" -e POSTGRES_DB=$dbname"
    [ "$username$password" ] && default_params="$default_params$username$password$db "
  fi
  echo "$service_version $default_params"
}

params-check::redis () {
  default_params='--net=host --rm --name redis -d -v /var/tmp/redis:/data'
  service_version="4.0"
  sudo mkdir -p /var/tmp/redis && sudo chmod -R 0777 /var/tmp/redis
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi

  echo "$service_version $default_params"
}

params-check::valkey () {
  default_params='--net=host --rm --name valkey -d -v /var/tmp/valkey:/data'
  service_version="8.1"
  sudo mkdir -p /var/tmp/valkey && sudo chmod -R 0777 /var/tmp/valkey
  params=""
  if [ "${1:0:1}" == "-" ]; then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi

  echo "$service_version $default_params"
}

params-check::mongodb () {
  default_params='--net=host --rm --name mongodb -d -v /var/tmp/mongodb:/home/mongo'
  sudo mkdir -p /var/tmp/mongodb && sudo chmod -R 0777 /var/tmp/mongodb
  service_version="4.1"
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi
  if [ "$default_params" != "$params" ];then
    username=""; password="" 
    for words in $params; do
      case $words in
       --username=* )
         username=$(echo $words|cut -d'=' -f2)
         [ "$username" ] && username=" -e MONGO_INITDB_ROOT_USERNAME=$username "
       ;;
       --password=* )
         password=$(echo $words|cut -d'=' -f2)
         [ "$password" ] && password=" -e MONGO_INITDB_ROOT_PASSWORD=$password "
       ;;
       *)
       ;;
      esac
    done
    default_params="$default_params$username$password "
  fi
  echo "$service_version $default_params"
}

params-check::elasticsearch () {
  local defaultEnv="-e 'discovery.type=single-node'"

  service_version="6.5"
  if [ "${1:0:1}" != "-" ];then
    service_version="${1:-$service_version}"
    shift
  fi
  defaultEnv="$defaultEnv $*"
  default_params=$(echo "docker run --net=host --rm --name elasticsearch -d $defaultEnv "|base64 --wrap=0)
  echo "$service_version $default_params"
}

params-check::opensearch () {
  local defaultEnv="-e 'discovery.type=single-node'"

  service_version="2"
  if [ "${1:0:1}" != "-" ];then
    service_version="${1:-$service_version}"
    shift
  fi
  defaultEnv="$defaultEnv $*"
  default_params=$(echo "docker run --net=host --rm --name opensearch -d $defaultEnv "|base64 --wrap=0)
  echo "$service_version $default_params"
}

params-check::main () {
  case "$1" in
    "mysql" )
      shift
      params-check::mysql $@
      ;;
    "postgres" )
      shift
      params-check::postgres $@
      ;;
    "postgis" )
      shift
      params-check::postgis $@
      ;;
    "redis" )
      shift
      params-check::redis $@
      ;;
    "valkey" )
      shift
      params-check::valkey $@
      ;;
    "mongodb" )
      shift
      params-check::mongodb $@
      ;;
    "elasticsearch" )
      shift
      params-check::elasticsearch $@
      ;;
    "opensearch" )
      shift
      params-check::opensearch $@
      ;;
    * )
      shift
      echo "$@"
      ;;
  esac
}

params-check::main "$@"
