#!/bin/bash

# Changing language versions

VERSION="0.1"
SUPPORTED_LANGUAGES=(go php ruby)
GO_URL="https://storage.googleapis.com/golang"
# Misc
DATE_FORMAT='%H:%M %d/%m/%Y'

################################################################################
# Generic function which executes the passed 'command' to install the version
# Globals:
#   language, language_version
# Arguments:
#   command
# Returns:
#  0, 1-127 (exit status of the language manager command)
install::install() {
  command=$1
  version::log "Changing '${language}' to version ${language_version}"
  echo "Im here"
  #eval $command $language_version
  ch_status=$?

  return $ch_status
}

install::install_ruby() {
#  echo "138.201.33.90 packages.rt.com" | sudo tee -a /etc/hosts
  response=$(curl -H "Host: packages.rt.com" --write-out %{http_code} --head --silent --output /dev/null http://138.201.33.90/ruby/${language_version}.tar.gz)
  if [[ $response -ne 200 ]] ; then
    rbenv install -s ${language_version}
  else
    curl -H "Host: packages.rt.com" --silent http://138.201.33.90/ruby/${language_version}.tar.gz --output ${language_version}.tar.gz
    tar -zxf ${language_version}.tar.gz
    mv ${language_version} ~/.rbenv/versions/
  fi
    rbenv rehash
    rbenv global ${language_version}

  return $?
}

install::install_go() {
 wget $GO_URL/go${language_version}.linux-amd64.tar.gz -P /tmp
 sudo mkdir -p /usr/local/golang/${language_version}
 sudo tar -C /usr/local/golang/${language_version} -xzf /tmp/go${language_version}.linux-amd64.tar.gz
 switch_go /usr/local/golang/{$language_version}/go

  return $?
}


install::install_php() {
  response=$(curl --write-out %{http_code} --head -H "Host: packages.rt.com" --silent --output /dev/null http://138.201.33.90/php/${language_version}.tar.gz)
  if [[ $response -ne 200 ]] ; then
    phpbrew install -j 4 ${language_version} +default +dbs +openssl -- --with-curl=/usr/local
    echo "date.timezone = UTC" >> "~/.phpbrew/php/php-${language_version}/etc/php.ini"
    phpbrew ext install imap -- --with-kerberos --with-imap-ssl
    phpbrew ext install gd -- --enable-gd-native-ttf --with-freetype-dir=/usr/lib/x86_64-linux-gnu
  else
    curl -H "Host: packages.rt.com" --silent http://138.201.33.90/php/${language_version}.tar.gz --output ${language_version}.tar.gz
    tar -zxf ${language_version}.tar.gz 
    mv php-${language_version} ~/.phpbrew/php/
  fi

  phpbrew switch {$language_version}
  return $?
}

################################################################################
# End of language installer wrappers
################################################################################


################################################################################
# Prints the usage
# Globals:
#   none
# Arguments:
#   none
# Returns:
#   none
install::usage() {
  echo -e "
################################################################################
sem-install ${VERSION} | Utility to install a selected languages version and activate it

Usage:
  sem-install language version
################################################################################"
}

################################################################################
# Helper to print date in the given format
# Globals:
#   DATE_FORMAT
# Arguments:
#   message
# Returns:
#   none
################################################################################
install::date() {
  date +"${DATE_FORMAT}"
}

################################################################################
# Helper to display info messages
# Globals:
#   none
# Arguments:
#   message
# Returns:
#   none
################################################################################
install::log() {
  echo -e "\n[$(version::date)]: $@" >&2
}

################################################################################
# Helper function to show error messages and to terminate execution on error
# Globals:
#   DATE_FORMAT
# Arguments:
#   message
# Returns:
#   1
################################################################################
install::err() {
  echo -e "\n! [$(version::date)]: $@" >&2

  return 1
}

################################################################################
# The main entrypoint to the script. Holds the switching logic.
# Globals:
#   SUPPORTED_LANGUAGES
# Arguments:
#   'language', 'version'
# Returns:
#   none
################################################################################
install::main() {
  if ! [[ $# -eq 2 ]]; then
    install::usage
    install::err "Unsupported number of arguments provided!"

    return $?
  fi

  language=$1
  language_version=$2

  for (( i=0; i < ${#SUPPORTED_LANGUAGES}; i++ )); do
    if [[ ${SUPPORTED_LANGUAGES[i]} -eq $laguage ]]; then
      fn_name="install::install_${language}"

      if ! [[ $(type -t $fn_name) == function ]]; then
        version::err "Function '${fn_name}' not implemented. Language '${language}' might not be supported."

        return $?
      fi

      install::install_${language} $language_version
      fn_status=$?

      if [[ fn_status -ne 0 ]]; then
        install::err "Failed to switch version.\nLog:\n$log"

        return $?
      fi

      install::log "Install and switch successful."

      break
    fi
  done
}

sem-install() {
  install::main "$@"
}

