#!/bin/bash

# Thin wrapper around starting background services with Docker

VERSION=0.6

# Misc
DATE_FORMAT='%H:%M %d/%m/%Y'


################################################################################
# Pull the passed Docker image
# Globals:
#   none
# Arguments:
#   image_name
# Returns:
#   0,1,...,n
#
# TODO: support multiple images
################################################################################
service::pull_image() {
  local image_name=$1

  if [[ -z $image_name ]]; then
    service:err "Image name can't be empty"
  fi

  if ! echo $image_name | grep -E '^[[:alnum:]]+(:[[:alnum:]]+.*)?$' &>/dev/null; then
    service::err "Invalid image name provided '${image_name}'"
  fi

  service::log "Pulling service image for '${image_name}'"
  service::run_cmd docker pull $image_name
}

service::start_mysql() {

  docker run --net=host --rm -d -e MYSQL_ALLOW_EMPTY_PASSWORD=true --name mysql mysql:5.6

  # run only if previous command exited successfully
  dockerize -wait tcp://0.0.0.0:3306 -timeout 30s

  # if not started in 30 seconds print logs and exit
  echo "Started mysql"
  echo "Use empty value for password"

  exit 0
}

service::start_postgres() {

  docker run --net=host --rm --name postgres -e POSTGRES_PASSWORD=semaphore -d postgres:9.6

  # run only if previous command exited successfully
  dockerize -wait tcp://0.0.0.0:5432 -timeout 30s

  # if not started in 30 seconds print logs and exit
  echo "Started postgres"
  echo "Use 'semaphore' value for password"

  exit 0
}

service::start_redis() {

  docker run --net=host --rm --name redis -d redis:4

  # run only if previous command exited successfully
  dockerize -wait tcp://0.0.0.0:6379 -timeout 30s

  # if not started in 30 seconds print logs and exit
  echo "Started redis"

  exit 0
}

service::start_memcached() {

  docker run --net=host --rm --name memcached -d memcached:1.5

  # run only if previous command exited successfully
  dockerize -wait tcp://0.0.0.0:11211 -timeout 30s

  # if not started in 30 seconds print logs and exit
  echo "Started memcached"

  exit 0
}

service::start() {
  service_name=$1
  if [ -z "$service_name" ]; then
    service::print_usage
    exit 1
  fi

  echo "SERVICE NAME $service_name"

  case "$service_name" in
    "mysql" )
      shift

      service::start_mysql "$@"
      ;;
    "postgres" )
      shift

      service::start_postgres "$@"
      ;;
    "redis" )
      shift

      service::start_redis "$@"
      ;;
    "memcached" )
      shift

      service::start_memcached "$@"
      ;;
    * )
      service::print_usage
      ;;
  esac

}


################################################################################
# Start a service with the defined Docker image
# Globals:
#   none
# Arguments:
#   image_name
# Returns:
#   0,1
# TODO: wait for service
################################################################################
service::old_start() {
  local image_name
  local service_name
  local command_status
  local command_log
  local service_check_log
  local pull_log

  image_name=$1
  service_name="${image_name%:*}"
  command_log=""
  command_status=""

  service::log "Starting '${service_name}' ..."

  service_check_log=$( service::status $service_name &>/dev/null )
  service_status=$?

  if [[ $service_status -eq 0 ]]; then
    service::log "'${service_name}' already started. Skipping."
  else
    pull_log=$(service::pull_image $image_name)
    pull_status=$?

    if ! [[ $pull_status -eq 0 ]]; then
      service::err "Failed to pull the image."
    fi

    command_log=$( service::run_cmd "docker run --net=host --rm -d $@ --name $service_name $image_name" )
    command_status=$?

    if ! [[ $command_status -eq 0 ]]; then
      service::err "Failed to start '${service_name}'"
    fi

    service::log "'${service_name}' successfully started."
    # the service needs a couple of secondns to become available
  fi
}


################################################################################
# Stop service if started
# Globals:
#   none
# Arguments:
#   service_name
# Returns:
#   0
################################################################################
service::stop() {
  local service_name
  local service_check_log

  service_name=$1
  service_check_log=$( service::status $service_name &>/dev/null )
  service_status=$?

  if [[ $service_status -eq 0 ]]; then
    stop_output=$( service::run_cmd docker stop $service_name )

    service::log "'${service_name}' stopped."
  else
    service::log "No running service with name '${service_name}' was found. Skipping."
  fi

  return 0
}


################################################################################
# Service status
# Globals:
#   none
# Arguments:
#   service_name
# Returns:
#   0,1...n
################################################################################
service::status() {
  local service_name
  local docker_ps

  service_name=$1
  docker_ps=$( service::run_cmd docker ps | grep $service_name &>/dev/null )
  service_status=$?

  if [[ $service_status -eq 0 ]]; then
    service::log "'${service_name}' running."
    service::log $(service::port_info $service_name)
  else
    service::log "'${service_name}' not running."
  fi

  return $service_status
}


################################################################################
# Helper for running commands with the ability to dry-run
# Globals:
#   DRYRUN
# Arguments:
#   command
# Returns:
#   0,1...n
################################################################################
service::run_cmd() {
  local cmd=$@
  local out=""
  local status=0

  if [[ -n $DRYRUN ]]; then
    service::log "Dry-running '${cmd}'"
  else
    out=$($cmd 2>&1)
    status=$?
  fi

  if ! [[ $status -eq 0 ]]; then
    service::err "Failed to run command '${cmd}'\n\nReason:\n${out}"
  fi

  echo "$out"
  return $status
}


################################################################################
# Gets port information about the running service
# Globals:
#   none
# Arguments:
#   service_name
# Returns:
#   port
################################################################################
service::port_info() {
  local service_name
  local service_check_log

  service_name=$1
  port_check_log=$( service::run_cmd sudo netstat -tlpn | grep $service_name 2>&1 )
  port_status=$?

  if [[ $service_status -eq 0 ]]; then
    listens_on=$( echo ${port_check_log} | awk '{print $4}' )

    echo "Listens on ${listens_on}"
  else
    echo "No port found for '${service_name}'."
  fi

  return 0
}


################################################################################
# Helper function to show log messages
# Globals:
#   DATE_FORMAT
# Arguments:
#   message
# Returns:
#   none
################################################################################
service::log() {
  echo -e "[$(date +"${DATE_FORMAT}")]: $@" >&2
}


################################################################################
# Helper function to show error messages and to terminate execution on error
# Globals:
#   DATE_FORMAT
# Arguments:
#   err, message
# Returns:
#   1
################################################################################
service::err() {
  echo -e "\n! [$(date +"${DATE_FORMAT}")]: $@\n" >&2

  exit 1
}


################################################################################
# Prints the program usage
# Globals:
#   VERSION
# Arguments:
#   None
# Returns:
#   None
################################################################################
service::print_usage() {
  echo -e "\nsem-service [start|stop|status] [service]\n"

  echo "Available services:"
  echo "mysql"
  echo "postgres"
  echo "redis"
  echo "memcached"
}


################################################################################
# Entry point to the script
################################################################################
service::main () {
  case "$1" in
    "start" )
      shift

      service::start "$@"
      ;;
    "stop" )
      shift

      service::stop "$@"
      ;;
    "status" )
      shift

      service::status "$@"
      ;;
    * )
      service::print_usage
      ;;
  esac
}

service::main "$@"
