#!/bin/bash
source ~/.toolbox/sem-install

# Changing language versions
VERSION="0.7"
SUPPORTED_SOFTWARE=(elixir go java php ruby python node c cpp erlang scala firefox)

# Misc
DATE_FORMAT='%H:%M %d/%m/%Y'
TOTAL_TIME=0

################################################################################
# Generic function which executes the passed 'command' to switch the version
# Globals:
#   language, language_version
# Arguments:
#   command
# Returns:
#  0, 1-127 (exit status of the language manager command)

version::metrics() {
  local cmd=$@
  local software=${1#"version::change_"}
  local version=$2
  local start
  local end
  local duration
  start=$(date +%s%3N)
  $cmd
  end=$(date +%s%3N)
  TOTAL_TIME=$(( $end - $start ))
  return 0
}
version::change() {
  command=$1
  version::log "Changing '${software}' to version ${software_version}"
  eval $command $software_version
  ch_status=$?
  return $ch_status
}
version::change_ruby() {
  if ! [ -d ~/.rbenv/versions/${software_version} ]; then
    sem-install ruby ${software_version}
  fi
  [ "$2" = "-f" ] && change_cmd="rbenv shell" || change_cmd="rbenv global"
  version::change "$change_cmd"
  return $?
}
version::change_node() {
  version::change "sem-install node"
  return $?
}
version::change_elixir() {
  kiex list | grep -q ${software_version}
  if [[ $? -gt 0 ]];then
    kiex install ${software_version}
  fi
  version::change "kiex use"
  return $?
}
version::change_go() {
  version::change "change-go-version"
  return $?
}
version::change_java() {
  version::change "change-java-version"
  return $?
}
version::change_php() {
  if ! [ -d ~/.phpbrew/php/php-${software_version} ]; then
    sem-install php ${software_version}
  fi
  software_version="php-${software_version}"
  version::change "phpbrew switch"
  return $?
}
version::change_python() {
  version::change "change-python-version"
  return $?
}
version::change_c() {
  version::change "change-gcc-version"
  return $?
}
version::change_cpp() {
  version::change "change-gcc-version"
  return $?
}
version::change_scala() {
  version::change "change-scala-version"
  return $?
}
version::change_erlang() {
  version::change "change-erlang-version"
  return $?
}
version::change_firefox() {
  local firefox_version=""
  case "${software_version}" in
    "52")firefox_version="esr-prev";;
    "68")firefox_version="esr";;
    "78")firefox_version="esr-new";;
    *)echo "Please choose one of 52, 68, 78";exit 1;;
  esac
  software_version="$firefox_version"
  version::change "change-firefox-version"
  return $?
}
################################################################################
# End of software manager wrappers
################################################################################


################################################################################
# Prints the usage
# Globals:
#   none
# Arguments:
#   none
# Returns:
#   none
version::usage() {
  echo -e "
################################################################################
sem-version ${VERSION} | Utility to change a selected software active version

Usage:
  sem-version software version
################################################################################"
}

################################################################################
# Helper to print date in the given format
# Globals:
#   DATE_FORMAT
# Arguments:
#   message
# Returns:
#   none
################################################################################
version::date() {
  date +"${DATE_FORMAT}"
}

################################################################################
# Helper to display info messages
# Globals:
#   none
# Arguments:
#   message
# Returns:
#   none
################################################################################
version::log() {
  echo -e "\n[$(version::date)]: $@" >&2
}

################################################################################
# Helper function to show error messages and to terminate execution on error
# Globals:
#   DATE_FORMAT
# Arguments:
#   message
# Returns:
#   1
################################################################################
version::err() {
  echo -e "\n! [$(version::date)]: $@" >&2

  return 1
}

################################################################################
# The main entrypoint to the script. Holds the switching logic.
# Globals:
#   SUPPORTED_SOFTWARE
# Arguments:
#   'software', 'version'
# Returns:
#   none
################################################################################
version::main() {
  if ! [[ $# -ge 2 ]]; then
    version::usage
    version::err "Unsupported number of arguments provided!"

    return $?
  fi

  software=$1
  software_version=$2
  force=$3

  for (( i=0; i < ${#SUPPORTED_SOFTWARE}; i++ )); do
    if [[ ${SUPPORTED_SOFTWARE[i]} -eq $software ]]; then
      fn_name="version::change_${software}"

      if ! [[ $(type -t $fn_name) == function ]]; then
        version::err "Function '${fn_name}' not implemented. Software '${software}' might not be supported."

        return $?
      fi

      version::metrics version::change_${software} $software_version $force
      fn_status=$?

      if [[ fn_status -ne 0 ]]; then
        version::err "Failed to switch version.\nLog:\n$log"
        echo "toolbox_sem_version{software=\"$software\",version=\"$version\",state='fail'} $TOTAL_TIME" >> /tmp/toolbox_semversion
        return $?
      else
        echo "toolbox_sem_version{software=\"$software\",version=\"$version\",state='success'} $TOTAL_TIME" >> /tmp/toolbox_semversion
      fi

      version::log "Switch successful."

      break
    fi
  done
}

sem-version() {
  if [[ `uname` == "Darwin" ]]; then
    echo "`sem-version` is not supported in this environment."
    echo "https://docs.semaphoreci.com/ci-cd-environment/sem-version-managing-language-versions-on-linux"
    return 1
  else
    version::main "$@"
  fi
}
