#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sem-version firefox 52
firefox --version | grep -q 52
sem-version firefox 78
firefox --version | grep -q 78
sem-version ruby 2.5.3
ruby --version | grep 2.5.3
sem-version ruby 2.5.2
ruby --version | grep 2.5.2
sem-version ruby 2.5.3
ruby --version | grep 2.5.3
sem-version ruby 2.3.7
ruby --version | grep 2.3.7
sem-version c 8
gcc --version | grep " 8."
sem-version cpp 7
gcc --version | grep " 7."
sem-version php 7.2.31
php -v | grep 7.2.31
sem-version php 7.0.33
php -v | grep 7.0.33
sem-version php 7.4
php -v | grep 7.4
phpbrew ext install xdebug
php -m | grep xdebug
sem-version php 7.3.19
php -m | grep magick
php -m | grep gd
php -m | grep imap
which composer | grep 7.3.19
sem-version elixir 1.7.4
time sem-version node 12.16.1
node --version | grep 12.16.1
nodejs --version | grep 12.16.1
time sem-version node 14
node --version | grep 14
sem-version ruby 2.6.6
ruby --version | grep 2.6.6
bundler --version | grep 2
mkdir ruby_test
echo "2.7.2" > ruby_test/.ruby-version
cd ruby_test
ruby --version| grep 2.7.2
sem-version ruby 2.3.7 -f
ruby --version| grep 2.3.7
kubectl version --client
sem-version kubectl 1.15.3
kubectl version --client | grep -q 1.15.3
