#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sem-service start elasticsearch
sleep 5
curl -XGET '0.0.0.0:9200/_cluster/health?pretty' -s | grep green
sem-service status elasticsearch
curl -XGET '0.0.0.0:9200' -s | grep 6.5
sem-service stop elasticsearch

sem-service start elasticsearch 6.6
sleep 5
curl -XGET '0.0.0.0:9200/_cluster/health?pretty' -s| grep green
sem-service stop elasticsearch

sem-service start elasticsearch 7.9
sleep 5
curl -XGET '0.0.0.0:9200' -s | grep 7.9
sem-service stop elasticsearch

sem-service start elasticsearch 7.10.0
sleep 5
curl -XGET '0.0.0.0:9200' -s | grep 7.10
sem-service stop elasticsearch
sleep 5

sem-service start elasticsearch 8.5.3 -e "xpack.security.enabled=false" -e "xpack.security.enrollment.enabled=false"
sleep 5
curl -XGET '0.0.0.0:9200' -s | grep 8.5.3
sem-service stop elasticsearch
sleep 5

sem-service start elasticsearch 8.9.2 -e "xpack.security.enabled=false" -e "xpack.security.enrollment.enabled=false"
sleep 10
curl -XGET '0.0.0.0:9200' -s | grep 8.9.2 
sem-service stop elasticsearch
sleep 5

sem-service start elasticsearch 8.11.3 -e "xpack.security.enabled=false" -e "xpack.security.enrollment.enabled=false" -e '"ES_JAVA_OPTS=-Xms256m -Xmx256m"'
sleep 10
curl -XGET '0.0.0.0:9200' -s | grep 8.11.3
docker inspect elasticsearch | grep '"ES_JAVA_OPTS=-Xms256m -Xmx256m"'
sem-service stop elasticsearch

