#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sem-service start elasticsearch
sleep 5
curl -XGET '0.0.0.0:9200/_cluster/health?pretty' -s | grep green

sem-service status elasticsearch
curl -XGET '0.0.0.0:9200' -s | grep 6.5

sem-service stop elasticsearch
sem-service start elasticsearch 6.6
sleep 5
curl -XGET '0.0.0.0:9200/_cluster/health?pretty' -s| grep green

sem-service stop elasticsearch
sem-service start elasticsearch 7.9
sleep 5
curl -XGET '0.0.0.0:9200' -s | grep 7.9

sem-service stop elasticsearch
sem-service start elasticsearch 7.10.0
sleep 5
curl -XGET '0.0.0.0:9200' -s | grep 7.10

sem-service stop elasticsearch
cat /tmp/toolbox_semservice
