#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sudo apt-get install -y mongodb-clients
sem-service start mongodb
curl http://localhost:27017 | grep "It looks like you are trying to access MongoDB over HTTP on the native driver port."

sem-service status mongodb
sem-service stop mongodb
sem-service start mongodb 3.2
curl http://localhost:27017 | grep "It looks like you are trying to access MongoDB over HTTP on the native driver port."

sem-service status mongodb
sem-service stop mongodb
sem-service stop mongodb
sem-service start mongodb 4.2 --username=xxx --password=xxx
echo "show dbs" | mongo -u "xxx" -p "xxx" 127.0.0.1  --authenticationDatabase "admin"

cat /tmp/toolbox_semservice
