#!/bin/bash
set -euo pipefail
IFS=$'\n\t'


sudo apt-get purge -y mongo-tools mongodb-clients
wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
sudo apt-get update
sudo apt-get install -y mongodb-org-tools mongodb-org-shell

#sudo apt-get install -y mongodb-clients

sem-service start mongodb
curl http://localhost:27017 | grep "It looks like you are trying to access MongoDB over HTTP on the native driver port."

sem-service status mongodb
sem-service stop mongodb
sem-service start mongodb 3.2
curl http://localhost:27017 | grep "It looks like you are trying to access MongoDB over HTTP on the native driver port."

sem-service status mongodb
sem-service stop mongodb
sem-service stop mongodb
sem-service start mongodb 4.2 --username=xxx --password=xxx
sleep 2
echo "show dbs" | mongo -u "xxx" -p "xxx" 127.0.0.1  --authenticationDatabase "admin"

sem-service status mongodb
sem-service stop mongodb
sem-service stop mongodb
sem-service start mongodb 5.0.1 --username=xxx --password=xxx
sleep 2
echo "show dbs" | mongo -u "xxx" -p "xxx" 127.0.0.1  --authenticationDatabase "admin"

sem-service status mongodb
sem-service stop mongodb
sem-service stop mongodb
sem-service start mongodb 5.0.8 --username=xxx --password=xxx
sleep 2
echo "show dbs" | mongo -u "xxx" -p "xxx" 127.0.0.1  --authenticationDatabase "admin"

sem-service status mongodb
sem-service stop mongodb
sem-service stop mongodb
sem-service start mongodb 5.0.9 --username=xxx --password=xxx
sleep 2
echo "show dbs" | mongo -u "xxx" -p "xxx" 127.0.0.1  --authenticationDatabase "admin"

sem-service status mongodb
sem-service stop mongodb
sem-service stop mongodb
sem-service start mongodb 5 --username=xxx --password=xxx
sleep 2
echo "show dbs" | mongo -u "xxx" -p "xxx" 127.0.0.1  --authenticationDatabase "admin"

cat /tmp/toolbox_semservice
