#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sem-service start mysql
mysql --host=0.0.0.0 -uroot -e "create database fooo"
mysql --host=0.0.0.0 -uroot -e "show databases" | grep fooo
mysql --host=0.0.0.0 -uroot -e 'SHOW VARIABLES like "version";' | grep 5.6
sem-service status mysql
sem-service stop mysql
sem-service start mysql 5.7
mysql --host=0.0.0.0 -uroot -e "create database fooo"
mysql --host=0.0.0.0 -uroot -e "show databases" | grep fooo
mysql --host=0.0.0.0 -uroot -e 'SHOW VARIABLES like "version";' | grep 5.7
sem-service status mysql
sem-service stop mysql
sem-service start mysql 8 --username=test --password=test --garbage else || true
sem-service stop mysql
sem-service start mysql --username=root --password=root
sem-service status mysql