#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sem-service start postgres
createdb -U postgres -h 0.0.0.0 fooo
psql -h 0.0.0.0 -U postgres -c "\l" | grep fooo
psql -h 0.0.0.0 -U postgres -c "SELECT version()" | grep 9.6
sem-service status postgres
sem-service stop postgres
sem-service start postgres 11
createdb -U postgres -h 0.0.0.0 fooo
psql -h 0.0.0.0 -U postgres -c "\l" | grep fooo
psql -h 0.0.0.0 -U postgres -c "SELECT version()" | grep 11
sem-service status postgres
sem-service stop postgres
sem-service start postgres 11 --username=xxx --password=xxx --db=xxx --garbage else
createdb -U xxx  -h 0.0.0.0 fooo
psql -h 0.0.0.0 -U xxx -c "\l"
psql -U xxx -c "SELECT version()" | grep 11
sem-service status postgres
sem-service stop postgres
sem-service start postgres 14
createdb -U postgres -h 0.0.0.0 fooo
psql -h 0.0.0.0 -U postgres -c "\l" | grep fooo
psql -h 0.0.0.0 -U postgres -c "SELECT version()" | grep 14
sem-service status postgres

sem-service stop postgres
sem-service start postgres 15.1
createdb -U postgres -h 0.0.0.0 fooo
psql -h 0.0.0.0 -U postgres -c "\l" | grep fooo
psql -h 0.0.0.0 -U postgres -c "SELECT version()" | grep 15.1
sem-service status postgres

sem-service stop postgres
sem-service start postgres 15
createdb -U postgres -h 0.0.0.0 fooo
psql -h 0.0.0.0 -U postgres -c "\l" | grep fooo
psql -h 0.0.0.0 -U postgres -c "SELECT version()" | grep 15
sem-service status postgres

sem-service stop postgres
sem-service start postgres 16
createdb -U postgres -h 0.0.0.0 fooo
psql -h 0.0.0.0 -U postgres -c "\l" | grep fooo
psql -h 0.0.0.0 -U postgres -c "SELECT version()" | grep 16
sem-service status postgres


cat /tmp/toolbox_semservice
