#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sem-service start redis
sem-service status redis
sem-service stop redis
sem-service start redis 5
sem-service status redis

sem-service stop redis
sem-service start redis 6.2.7
sem-service status redis

sem-service stop redis
sem-service start redis 7.0.5
sem-service status redis

sem-service stop redis
sem-service start redis 7.2.4
sem-service status redis

sem-service stop redis
sem-service start redis 8.0.2
sem-service status redis

cat /tmp/toolbox_semservice
